name: Node CI

on:
   - push
   - pull_request

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: make lint
      - run: make test
